### ISSUE TITLE
HTMLKit erroneous HTMLText serialization and entity decoding

### ISSUE THREAD

**Issue by dsanghan** [iabudiab/HTMLKit#16]
Let's say you have the following html:

```
<html>
  <body>
    <div> &lt;example&gt; </div>
  </body>
</html>
```

Then on:
```
HTMLDocument *doc = [HTMLDocument documentWithString:html];
```
and printing out the html via `doc.rootElement.outerHTML` you get partially decoded entities:
`<html><head></head><body>    <div>&lt;example></div>        </body></html>` where `&lt;` is left as is, and `&gt;` is decoded.

Not sure what the correct thing to do here is.

**Comment by iabudiab** [comment]
@dsanghan Hey there! I'll take a look at this as soon as I get home. I'll keep you posted.

**Comment by iabudiab** [comment]
@dsanghan Hey again! It's a 🐛 But don't worry, I've already fixed it and a new version is being released. Thanks a lot for reporting this 👍 

I've also revisited all the other serialization methods and guess what? `HTMLElement` suffers from the same bug.

I'll close this once the code is pushed and released.
