### ISSUE TITLE
"use_frameworks!" in the podfile is redundant

### ISSUE THREAD

**Issue by skyforcc** [iabudiab/HTMLKit#18]
When I deleted this statement, I can use the command "import <HTMLKit/HTMLKit.h>", or there is other way to use this kit?

**Comment by iabudiab** [comment]
@skyforcc Hey there. Yes, the `use frameworks!` is redundant. With earlier version of CocoaPods it was needed, now you can just drop it. I'll close the issue and update the Readme in the meantime.
Cheers!
