### ISSUE TITLE
Build error "Expected unqualified-id"

### ISSUE THREAD

**Issue by ducminh1012** [iabudiab/HTMLKit#19]
Hello, 
I have this error when building project with this library.
[https://imgur.com/a/X9nOn](https://imgur.com/a/X9nOn)
Could you help me resolve this?

Thanks,
...

**Comment by iabudiab** [comment]
@ducminh1012 Hey there, I'll try to figure it out, and it would help a lot if you could give me more information about your project:

- Are you using Carthage, CocoaPods, Manual?
- Do you C++ sources in your project (I remember seeing this error together with C++ more than once)
- Do you have a sample project that I could use to troubleshoot the issue?

**Comment by ducminh1012** [comment]
Hi @iabudiab,
Yes, I'm using CocoaPods and in my project, there are some libs in C++.
I think the problem could be the 'not' is one of the keywords in C++.

**Comment by iabudiab** [comment]
Hey @ducminh1012 

It seems like the C++ stuff is getting in the way. But we're getting there.

- Are you using `.cpp` files together with ObjC? If so, you could try using the `.mm` extension. That way the code would be built as Objective-C++ which honors both languages correctly.
- Are you calling ObjC from C++ or the other way around?
- Do you have a minimal sample project I could use for testing?

**Comment by ducminh1012** [comment]
Hello @iabudiab 

Using the Objective-C++ solved my issue. Thank you for your help!
