### ISSUE TITLE
Implement DOM Ranges

### ISSUE THREAD

**Issue by gneil90** [iabudiab/HTMLKit#2]
Could we please discuss implementing DOM range feature? I would be pleased to contribute for this part of project

**Comment by iabudiab** [comment]
Hey, of course we could. And if you want to help, even better 👍

I would start by reading and understanding the [relevant specification](https://dom.spec.whatwg.org/#ranges) and all that is necessary for DOM Ranges to be implemented.

I don't know how deep you are already are in the code base, but a good starting point would be to introduce the [length property](https://dom.spec.whatwg.org/#concept-node-length) for `HTMLNode` and its subclasses.

The trickiest part in my opinion are the DOM mutations and their effects on the ranges and vice versa. I'll get back to you once I've read the spec and analyzed it.

Let me know if you have any further thoughts. Will be glad to discuss them.

**Comment by iabudiab** [comment]
`DOM Ranges` are implemented now in the `develop` branch 🎉 (more specifically this commit: 542bc26ff9b38c8d792093633daf676db3fc615e)
I'll release v1.1.0 as soon as I've done some housekeeping.

Closing this issue for now. 
For bugs or problems related to `DOM Ranges` please open new issues.
