### ISSUE TITLE
NSInvalidArgumentException raised when trying to change an attribute of a cloned element

### ISSUE THREAD

**Issue by vladvlasov256** [iabudiab/HTMLKit#20]
Impossible to change an attribute of a cloned element if its original element had attributes.

An example:
```
HTMLElement *element = [HTMLElement new];
element.elementId = @"originalId";
    
HTMLElement *clone = [element cloneNodeDeep:YES];
NSString *cloneId = @"cloneId";
clone.elementId = cloneId
```

The last line raises the **NSInvalidArgumentException**:
_[__NSSingleEntryDictionaryI setObject:forKeyedSubscript:]: unrecognized selector sent to instance 0x7fcbd143e150_

The root cause is the HTMLElement copy method:
```
- (id)copyWithZone:(NSZone *)zone
{
	...
	copy->_attributes = [_attributes copy];
	...
}
```

If the **_attributes** is not nil a copy will be a NSDictionary not a HTMLOrderedDictionary.

**Comment by iabudiab** [comment]
@CRivlaldo Hey, great catch! Thanks for reporting!
