### ISSUE TITLE
nextSiblingElement returns itself for any HTMLElement

### ISSUE THREAD

**Issue by vladvlasov256** [iabudiab/HTMLKit#28]
HTMLNode.m, line 128

```
- (HTMLElement *)nextSiblingElement
{
	HTMLNode *node = self.previousSibling;
	while (node && node.nodeType != HTMLNodeElement) {
		node = node.nextSibling;
	}
	return node.asElement;
}
```

Because of an iteration starts with a previous element the next sibling element it the element itself. Possibly a typo.

**Comment by iabudiab** [comment]
@CRivlaldo Nice catch! Thanks for the fix. Will release soon.
