### ISSUE TITLE
Xcode12.5: 'new' is unavailable 

### ISSUE THREAD

**Issue by alflix** [iabudiab/HTMLKit#43]
Getting this error at build time in Xcode 12.5
HTMLParser.m: 'new' is unavailable 'init' has been explicitly marked unavailable here

<img width="2043" alt="Screen Shot 2021-04-28 at 11 02 32 AM" src="https://user-images.githubusercontent.com/4870617/116340139-3dd1c480-a811-11eb-883b-51001dba5830.png">

**Comment by iabudiab** [comment]
@alflix Hey there 👋 It should be fixed in ~~4.1.0~~ 4.20
Let me know if you have any other problems

**Comment by irrevaldy** [comment]
@iabudiab is it already fixed? I found the same issue please help
